# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

---
- name: Include distribution vars
  include_vars:
    file: "{{ ansible_distribution | lower }}.yml"

- name: Check for existing required binaries
  stat:
    path: "{{ item }}"
  with_items: "{{ validation_binaries }}"
  register: binary
  failed_when: binary.stat.executable == False
