[package]
name = "Sgxcovenclave"
version = "1.0.0"
authors = ["Baidu"]

[lib]
name = "sgxcovenclave"
crate-type = ["staticlib"]

[features]
default = []
cov = ["sgx_cov"]

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { git = "https://github.com/baidu/rust-sgx-sdk.git" }
sgx_tstd = { git = "https://github.com/baidu/rust-sgx-sdk.git" }
sgx_trts = { git = "https://github.com/baidu/rust-sgx-sdk.git" }
sgx_cov  = { git = "https://github.com/baidu/rust-sgx-sdk.git", optional = true }
