# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

---
- name: Include distribution vars
  include_vars:
    file: "{{ ansible_distribution | lower }}.yml"

- name: Include distribution release specific vars
  include_vars:
    file: "{{ ansible_distribution_release | lower }}.yml"

- name: Install the dkms package
  apt:
    name:
      - "dkms"
    state: present
    update_cache: yes
    install_recommends: no

- name: Populate service facts
  service_facts:

- name: Ensure aesmd service stopped
  service:
    name: aesmd
    state: stopped
  when: "'aesmd.service' in ansible_facts.services"

- name: Download Intel SGX DCAP Driver
  get_url:
    url: "{{intel_sgx_w_flc_driver_url}}"
    dest: /tmp/sgx_linux_x64_driver.bin
    mode: 0755
    timeout: 120
  retries: 3
  when: flc_enabled|bool

- name: Download Intel SGX1 Driver
  get_url:
    url: "{{intel_sgx1_driver_url}}"
    dest: /tmp/sgx_linux_x64_driver.bin
    mode: 0755
    timeout: 120
  retries: 3
  when: not flc_enabled|bool

- name: Install the Intel SGX DCAP Driver
  command: /tmp/sgx_linux_x64_driver.bin

- name: Remove the Intel SGX DCAP Driver installer
  file:
    path: /tmp/sgx_linux_x64_driver.bin
    state: absent

- name: Ensure aesmd service running
  service:
    name: aesmd
    state: started
    enabled: yes
  when: "'aesmd.service' in ansible_facts.services"
