[package]
name = "enclave1"
version = "1.0.0"
authors = ["Baidu"]

[lib]
name = "enclave1"
crate-type = ["staticlib"]

[features]
default = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk.git" }

[dependencies]
attestation = {path = "../attestation/"}
