[package]
authors = ["The Rust Project Developers"]
name = "sgx_unwind"
version = "0.0.1"
build = "build.rs"
repository = "https://github.com/baidu/rust-sgx-sdk"
license-file = "LICENSE"
documentation = "https://dingelish.github.io/"
description = "Rust SGX SDK provides the ability to write Intel SGX applications in Rust Programming Language."

include = [
    "LICENSE",
    "Readme.md",
    "Cargo.toml",
    "macros.rs",
    "build.rs",
    "libunwind.rs",
    "lib.rs",
]

[lib]
name = "sgx_unwind"
path = "lib.rs"
test = false
bench = false
doc = false

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_trts = { path = "../sgx_trts" }
