# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

---
- name: Include distribution vars
  include_vars:
    file: "{{ ansible_distribution | lower }}.yml"

- name: Check for existing required files
  stat:
    path: "{{ item }}"
  with_items: "{{ validation_files }}"
  register: file
  failed_when: file.stat.exists == False
