[package]
name = "runner"
version = "0.1.0"
authors = ["Fortanix, Inc."]
license = "MPL-2.0"

[dependencies]
aesm-client = { version = "0.2", features = ["sgxs"]}
enclave-runner = "0.2"
sgxs-loaders = "0.2"
byteorder = "1.0"
libc = "0.2"
