# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

---
intel_sgx_packages:
  - "libsgx-enclave-common"
  - "libsgx-enclave-common-dev"

intel_dcap_packages:
  - "libsgx-dcap-ql"
  - "libsgx-dcap-ql-dev"

driver_validation_directories:
  - "/opt/intel/sgxdriver"

packages_validation_directories:
  - "/opt/intel/libsgx-enclave-common"

packages_validation_files:
  - "/usr/lib/x86_64-linux-gnu/libsgx_dcap_ql.so"
