[package]
name = "Filesampleenclave"
version = "1.0.0"
authors = ["Baidu"]

[lib]
name = "filesampleenclave"
crate-type = ["staticlib"]

[features]
default = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_tstd = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk.git" }
sgx_rand = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk.git" }
sgx_serialize = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk.git" }

[dependencies]
sgx_rand_derive = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk.git" }
sgx_serialize_derive = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk.git" }
