# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

---
ci_apt_packages:
  - "automake"
  - "dh-exec"
  - "dpkg-dev"
  - "gawk"
  - "git"
  - "libmbedtls10"
  - "sudo"
  - "libcurl3"
  - "libprotobuf9v5"
