[package]
name = "pcl-user"
version = "0.1.0"
authors = ["Yu Ding <dingyu02@baidu.com>"]
build = "build.rs"

[dependencies]
chrono      = "0.4.5"
webpki      = "0.18.1"
rustls      = { version = "0.13.0", features = ["dangerous_configuration"] }
itertools   = "*"
sgx_types   = { path = "../../../sgx_types" }
base64      = "0.9.2"
untrusted   = "*"
serde_json  = "1.0.24"
num-bigint  = "*"
bit-vec     = "*"
hex         = "*"
ue_send_recv= { path = "ue_send_recv" }

[build-dependencies]
itertools   = "*"
